version: '3'
services:
   web:
      build: .
      ports:
         - "3000:3000"
      links:
         - db
   db:
      image: "cassandra:latest"
      volumes:
         - ./data:/var/lib/cassandra
